### ISSUE TITLE
404 - Page not found 

### ISSUE THREAD

**Issue by uri870** [raymondcho/RelationalDatabaseTools#1]
The page http://raymondcho.net/RelationalDatabaseTools/RelationalDatabaseTools is not found and producing a 404 error.

**Comment by raymondcho** [comment]
Thanks for notifying me. Seems the implicit redirect to .html isn't working and so I have updated the link to go directly to http://raymondcho.net/RelationalDatabaseTools/RelationalDatabaseTools.html.
